/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package resources;

public class intrealT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected intrealT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(intrealT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qhullJNI.delete_intrealT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI(int value) {
    qhullJNI.intrealT_i_set(swigCPtr, this, value);
  }

  public int getI() {
    return qhullJNI.intrealT_i_get(swigCPtr, this);
  }

  public void setR(double value) {
    qhullJNI.intrealT_r_set(swigCPtr, this, value);
  }

  public double getR() {
    return qhullJNI.intrealT_r_get(swigCPtr, this);
  }

  public intrealT() {
    this(qhullJNI.new_intrealT(), true);
  }

}
