/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package resources;

public class mergeT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected mergeT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mergeT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qhullJNI.delete_mergeT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAngle(double value) {
    qhullJNI.mergeT_angle_set(swigCPtr, this, value);
  }

  public double getAngle() {
    return qhullJNI.mergeT_angle_get(swigCPtr, this);
  }

  public void setDistance(double value) {
    qhullJNI.mergeT_distance_set(swigCPtr, this, value);
  }

  public double getDistance() {
    return qhullJNI.mergeT_distance_get(swigCPtr, this);
  }

  public void setFacet1(SWIGTYPE_p_facetT value) {
    qhullJNI.mergeT_facet1_set(swigCPtr, this, SWIGTYPE_p_facetT.getCPtr(value));
  }

  public SWIGTYPE_p_facetT getFacet1() {
    long cPtr = qhullJNI.mergeT_facet1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_facetT(cPtr, false);
  }

  public void setFacet2(SWIGTYPE_p_facetT value) {
    qhullJNI.mergeT_facet2_set(swigCPtr, this, SWIGTYPE_p_facetT.getCPtr(value));
  }

  public SWIGTYPE_p_facetT getFacet2() {
    long cPtr = qhullJNI.mergeT_facet2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_facetT(cPtr, false);
  }

  public void setVertex1(SWIGTYPE_p_vertexT value) {
    qhullJNI.mergeT_vertex1_set(swigCPtr, this, SWIGTYPE_p_vertexT.getCPtr(value));
  }

  public SWIGTYPE_p_vertexT getVertex1() {
    long cPtr = qhullJNI.mergeT_vertex1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vertexT(cPtr, false);
  }

  public void setVertex2(SWIGTYPE_p_vertexT value) {
    qhullJNI.mergeT_vertex2_set(swigCPtr, this, SWIGTYPE_p_vertexT.getCPtr(value));
  }

  public SWIGTYPE_p_vertexT getVertex2() {
    long cPtr = qhullJNI.mergeT_vertex2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vertexT(cPtr, false);
  }

  public void setRidge1(SWIGTYPE_p_ridgeT value) {
    qhullJNI.mergeT_ridge1_set(swigCPtr, this, SWIGTYPE_p_ridgeT.getCPtr(value));
  }

  public SWIGTYPE_p_ridgeT getRidge1() {
    long cPtr = qhullJNI.mergeT_ridge1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ridgeT(cPtr, false);
  }

  public void setRidge2(SWIGTYPE_p_ridgeT value) {
    qhullJNI.mergeT_ridge2_set(swigCPtr, this, SWIGTYPE_p_ridgeT.getCPtr(value));
  }

  public SWIGTYPE_p_ridgeT getRidge2() {
    long cPtr = qhullJNI.mergeT_ridge2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ridgeT(cPtr, false);
  }

  public void setMergetype(mergeType value) {
    qhullJNI.mergeT_mergetype_set(swigCPtr, this, value.swigValue());
  }

  public mergeType getMergetype() {
    return mergeType.swigToEnum(qhullJNI.mergeT_mergetype_get(swigCPtr, this));
  }

  public mergeT() {
    this(qhullJNI.new_mergeT(), true);
  }

}
