/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package resources;

public final class qh_RIDGE {
  public final static qh_RIDGE qh_RIDGEall = new qh_RIDGE("qh_RIDGEall", qhullJNI.qh_RIDGEall_get());
  public final static qh_RIDGE qh_RIDGEinner = new qh_RIDGE("qh_RIDGEinner");
  public final static qh_RIDGE qh_RIDGEouter = new qh_RIDGE("qh_RIDGEouter");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static qh_RIDGE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + qh_RIDGE.class + " with value " + swigValue);
  }

  private qh_RIDGE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private qh_RIDGE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private qh_RIDGE(String swigName, qh_RIDGE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static qh_RIDGE[] swigValues = { qh_RIDGEall, qh_RIDGEinner, qh_RIDGEouter };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

