/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package resources;

public class qhmemT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected qhmemT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(qhmemT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qhullJNI.delete_qhmemT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBUFsize(int value) {
    qhullJNI.qhmemT_BUFsize_set(swigCPtr, this, value);
  }

  public int getBUFsize() {
    return qhullJNI.qhmemT_BUFsize_get(swigCPtr, this);
  }

  public void setBUFinit(int value) {
    qhullJNI.qhmemT_BUFinit_set(swigCPtr, this, value);
  }

  public int getBUFinit() {
    return qhullJNI.qhmemT_BUFinit_get(swigCPtr, this);
  }

  public void setTABLEsize(int value) {
    qhullJNI.qhmemT_TABLEsize_set(swigCPtr, this, value);
  }

  public int getTABLEsize() {
    return qhullJNI.qhmemT_TABLEsize_get(swigCPtr, this);
  }

  public void setNUMsizes(int value) {
    qhullJNI.qhmemT_NUMsizes_set(swigCPtr, this, value);
  }

  public int getNUMsizes() {
    return qhullJNI.qhmemT_NUMsizes_get(swigCPtr, this);
  }

  public void setLASTsize(int value) {
    qhullJNI.qhmemT_LASTsize_set(swigCPtr, this, value);
  }

  public int getLASTsize() {
    return qhullJNI.qhmemT_LASTsize_get(swigCPtr, this);
  }

  public void setALIGNmask(int value) {
    qhullJNI.qhmemT_ALIGNmask_set(swigCPtr, this, value);
  }

  public int getALIGNmask() {
    return qhullJNI.qhmemT_ALIGNmask_get(swigCPtr, this);
  }

  public void setFreelists(SWIGTYPE_p_p_void value) {
    qhullJNI.qhmemT_freelists_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getFreelists() {
    long cPtr = qhullJNI.qhmemT_freelists_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public void setSizetable(SWIGTYPE_p_int value) {
    qhullJNI.qhmemT_sizetable_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getSizetable() {
    long cPtr = qhullJNI.qhmemT_sizetable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setIndextable(SWIGTYPE_p_int value) {
    qhullJNI.qhmemT_indextable_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getIndextable() {
    long cPtr = qhullJNI.qhmemT_indextable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setCurbuffer(SWIGTYPE_p_void value) {
    qhullJNI.qhmemT_curbuffer_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getCurbuffer() {
    long cPtr = qhullJNI.qhmemT_curbuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFreemem(SWIGTYPE_p_void value) {
    qhullJNI.qhmemT_freemem_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getFreemem() {
    long cPtr = qhullJNI.qhmemT_freemem_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFreesize(int value) {
    qhullJNI.qhmemT_freesize_set(swigCPtr, this, value);
  }

  public int getFreesize() {
    return qhullJNI.qhmemT_freesize_get(swigCPtr, this);
  }

  public void setTempstack(setT value) {
    qhullJNI.qhmemT_tempstack_set(swigCPtr, this, setT.getCPtr(value), value);
  }

  public setT getTempstack() {
    long cPtr = qhullJNI.qhmemT_tempstack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new setT(cPtr, false);
  }

  public void setFerr(SWIGTYPE_p_FILE value) {
    qhullJNI.qhmemT_ferr_set(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(value));
  }

  public SWIGTYPE_p_FILE getFerr() {
    long cPtr = qhullJNI.qhmemT_ferr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public void setIStracing(int value) {
    qhullJNI.qhmemT_IStracing_set(swigCPtr, this, value);
  }

  public int getIStracing() {
    return qhullJNI.qhmemT_IStracing_get(swigCPtr, this);
  }

  public void setCntquick(int value) {
    qhullJNI.qhmemT_cntquick_set(swigCPtr, this, value);
  }

  public int getCntquick() {
    return qhullJNI.qhmemT_cntquick_get(swigCPtr, this);
  }

  public void setCntshort(int value) {
    qhullJNI.qhmemT_cntshort_set(swigCPtr, this, value);
  }

  public int getCntshort() {
    return qhullJNI.qhmemT_cntshort_get(swigCPtr, this);
  }

  public void setCntlong(int value) {
    qhullJNI.qhmemT_cntlong_set(swigCPtr, this, value);
  }

  public int getCntlong() {
    return qhullJNI.qhmemT_cntlong_get(swigCPtr, this);
  }

  public void setFreeshort(int value) {
    qhullJNI.qhmemT_freeshort_set(swigCPtr, this, value);
  }

  public int getFreeshort() {
    return qhullJNI.qhmemT_freeshort_get(swigCPtr, this);
  }

  public void setFreelong(int value) {
    qhullJNI.qhmemT_freelong_set(swigCPtr, this, value);
  }

  public int getFreelong() {
    return qhullJNI.qhmemT_freelong_get(swigCPtr, this);
  }

  public void setTotbuffer(int value) {
    qhullJNI.qhmemT_totbuffer_set(swigCPtr, this, value);
  }

  public int getTotbuffer() {
    return qhullJNI.qhmemT_totbuffer_get(swigCPtr, this);
  }

  public void setTotdropped(int value) {
    qhullJNI.qhmemT_totdropped_set(swigCPtr, this, value);
  }

  public int getTotdropped() {
    return qhullJNI.qhmemT_totdropped_get(swigCPtr, this);
  }

  public void setTotfree(int value) {
    qhullJNI.qhmemT_totfree_set(swigCPtr, this, value);
  }

  public int getTotfree() {
    return qhullJNI.qhmemT_totfree_get(swigCPtr, this);
  }

  public void setTotlong(int value) {
    qhullJNI.qhmemT_totlong_set(swigCPtr, this, value);
  }

  public int getTotlong() {
    return qhullJNI.qhmemT_totlong_get(swigCPtr, this);
  }

  public void setMaxlong(int value) {
    qhullJNI.qhmemT_maxlong_set(swigCPtr, this, value);
  }

  public int getMaxlong() {
    return qhullJNI.qhmemT_maxlong_get(swigCPtr, this);
  }

  public void setTotshort(int value) {
    qhullJNI.qhmemT_totshort_set(swigCPtr, this, value);
  }

  public int getTotshort() {
    return qhullJNI.qhmemT_totshort_get(swigCPtr, this);
  }

  public void setTotunused(int value) {
    qhullJNI.qhmemT_totunused_set(swigCPtr, this, value);
  }

  public int getTotunused() {
    return qhullJNI.qhmemT_totunused_get(swigCPtr, this);
  }

  public void setCntlarger(int value) {
    qhullJNI.qhmemT_cntlarger_set(swigCPtr, this, value);
  }

  public int getCntlarger() {
    return qhullJNI.qhmemT_cntlarger_get(swigCPtr, this);
  }

  public void setTotlarger(int value) {
    qhullJNI.qhmemT_totlarger_set(swigCPtr, this, value);
  }

  public int getTotlarger() {
    return qhullJNI.qhmemT_totlarger_get(swigCPtr, this);
  }

  public qhmemT() {
    this(qhullJNI.new_qhmemT(), true);
  }

}
