/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package resources;

public interface qhullConstants {
  public final static int qhDEFuser = qhullJNI.qhDEFuser_get();
  public final static int qh_FILENAMElen = qhullJNI.qh_FILENAMElen_get();
  public final static int MSG_TRACE0 = qhullJNI.MSG_TRACE0_get();
  public final static int MSG_TRACE1 = qhullJNI.MSG_TRACE1_get();
  public final static int MSG_TRACE2 = qhullJNI.MSG_TRACE2_get();
  public final static int MSG_TRACE3 = qhullJNI.MSG_TRACE3_get();
  public final static int MSG_TRACE4 = qhullJNI.MSG_TRACE4_get();
  public final static int MSG_TRACE5 = qhullJNI.MSG_TRACE5_get();
  public final static int MSG_ERROR = qhullJNI.MSG_ERROR_get();
  public final static int MSG_WARNING = qhullJNI.MSG_WARNING_get();
  public final static int MSG_STDERR = qhullJNI.MSG_STDERR_get();
  public final static int MSG_OUTPUT = qhullJNI.MSG_OUTPUT_get();
  public final static int MSG_QHULL_ERROR = qhullJNI.MSG_QHULL_ERROR_get();
  public final static int MSG_FIX = qhullJNI.MSG_FIX_get();
  public final static int MSG_MAXLEN = qhullJNI.MSG_MAXLEN_get();
  public final static int qh_OPTIONline = qhullJNI.qh_OPTIONline_get();
  public final static int REALfloat = qhullJNI.REALfloat_get();
  public final static int qh_REALdigits = qhullJNI.qh_REALdigits_get();
  public final static String qh_REAL_1 = qhullJNI.qh_REAL_1_get();
  public final static String qh_REAL_2n = qhullJNI.qh_REAL_2n_get();
  public final static String qh_REAL_3n = qhullJNI.qh_REAL_3n_get();
  public final static int DEFcountT = qhullJNI.DEFcountT_get();
  public final static int qh_CLOCKtype = qhullJNI.qh_CLOCKtype_get();
  public final static double qh_SECticks = qhullJNI.qh_SECticks_get();
  public final static int qh_RANDOMtype = qhullJNI.qh_RANDOMtype_get();
  public final static int qh_ORIENTclock = qhullJNI.qh_ORIENTclock_get();
  public final static double qh_JOGGLEdefault = qhullJNI.qh_JOGGLEdefault_get();
  public final static double qh_JOGGLEincrease = qhullJNI.qh_JOGGLEincrease_get();
  public final static int qh_JOGGLEretry = qhullJNI.qh_JOGGLEretry_get();
  public final static int qh_JOGGLEagain = qhullJNI.qh_JOGGLEagain_get();
  public final static double qh_JOGGLEmaxincrease = qhullJNI.qh_JOGGLEmaxincrease_get();
  public final static int qh_JOGGLEmaxretry = qhullJNI.qh_JOGGLEmaxretry_get();
  public final static int qh_HASHfactor = qhullJNI.qh_HASHfactor_get();
  public final static int qh_VERIFYdirect = qhullJNI.qh_VERIFYdirect_get();
  public final static int qh_INITIALsearch = qhullJNI.qh_INITIALsearch_get();
  public final static int qh_INITIALmax = qhullJNI.qh_INITIALmax_get();
  public final static int qh_MEMbufsize = qhullJNI.qh_MEMbufsize_get();
  public final static int qh_MEMinitbuf = qhullJNI.qh_MEMinitbuf_get();
  public final static double qh_INFINITE = qhullJNI.qh_INFINITE_get();
  public final static double qh_DEFAULTbox = qhullJNI.qh_DEFAULTbox_get();
  public final static double qh_DEFAULTzbox = qhullJNI.qh_DEFAULTzbox_get();
  public final static int qh_COMPUTEfurthest = qhullJNI.qh_COMPUTEfurthest_get();
  public final static int qh_KEEPstatistics = qhullJNI.qh_KEEPstatistics_get();
  public final static int qh_MAXoutside = qhullJNI.qh_MAXoutside_get();
  public final static int qh_QHpointer = qhullJNI.qh_QHpointer_get();
  public final static int qh_QUICKhelp = qhullJNI.qh_QUICKhelp_get();
  public final static int qh_BESTcentrum = qhullJNI.qh_BESTcentrum_get();
  public final static int qh_BESTcentrum2 = qhullJNI.qh_BESTcentrum2_get();
  public final static int qh_BESTnonconvex = qhullJNI.qh_BESTnonconvex_get();
  public final static int qh_COPLANARratio = qhullJNI.qh_COPLANARratio_get();
  public final static int qh_DIMmergeVertex = qhullJNI.qh_DIMmergeVertex_get();
  public final static int qh_DIMreduceBuild = qhullJNI.qh_DIMreduceBuild_get();
  public final static int qh_MAXcheckpoint = qhullJNI.qh_MAXcheckpoint_get();
  public final static int qh_MAXcoplanarcentrum = qhullJNI.qh_MAXcoplanarcentrum_get();
  public final static int qh_MAXnewcentrum = qhullJNI.qh_MAXnewcentrum_get();
  public final static int qh_MAXnewmerges = qhullJNI.qh_MAXnewmerges_get();
  public final static double qh_RATIOconcavehorizon = qhullJNI.qh_RATIOconcavehorizon_get();
  public final static double qh_RATIOconvexmerge = qhullJNI.qh_RATIOconvexmerge_get();
  public final static double qh_RATIOcoplanarapex = qhullJNI.qh_RATIOcoplanarapex_get();
  public final static double qh_RATIOcoplanaroutside = qhullJNI.qh_RATIOcoplanaroutside_get();
  public final static double qh_RATIOmaxsimplex = qhullJNI.qh_RATIOmaxsimplex_get();
  public final static int qh_RATIOnearinside = qhullJNI.qh_RATIOnearinside_get();
  public final static double qh_RATIOpinchedsubridge = qhullJNI.qh_RATIOpinchedsubridge_get();
  public final static double qh_RATIOtrypinched = qhullJNI.qh_RATIOtrypinched_get();
  public final static double qh_RATIOtwisted = qhullJNI.qh_RATIOtwisted_get();
  public final static double qh_MAXnarrow = qhullJNI.qh_MAXnarrow_get();
  public final static double qh_WARNnarrow = qhullJNI.qh_WARNnarrow_get();
  public final static int qh_WIDEcoplanar = qhullJNI.qh_WIDEcoplanar_get();
  public final static int qh_WIDEduplicate = qhullJNI.qh_WIDEduplicate_get();
  public final static int qh_WIDEdupridge = qhullJNI.qh_WIDEdupridge_get();
  public final static int qh_WIDEmaxoutside = qhullJNI.qh_WIDEmaxoutside_get();
  public final static int qh_WIDEmaxoutside2 = qhullJNI.qh_WIDEmaxoutside2_get();
  public final static int qh_WIDEpinched = qhullJNI.qh_WIDEpinched_get();
  public final static int qh_ZEROdelaunay = qhullJNI.qh_ZEROdelaunay_get();
  public final static int qhDEFqhulla = qhullJNI.qhDEFqhulla_get();
  public final static int qhDEFgeom = qhullJNI.qhDEFgeom_get();
  public final static int qhDEFio = qhullJNI.qhDEFio_get();
  public final static int qh_MAXfirst = qhullJNI.qh_MAXfirst_get();
  public final static double qh_MINradius = qhullJNI.qh_MINradius_get();
  public final static double qh_GEOMepsilon = qhullJNI.qh_GEOMepsilon_get();
  public final static String qh_WHITESPACE = qhullJNI.qh_WHITESPACE_get();
  public final static int qhDEFmem = qhullJNI.qhDEFmem_get();
  public final static int qhmem_ERRmem = qhullJNI.qhmem_ERRmem_get();
  public final static int qhmem_ERRqhull = qhullJNI.qhmem_ERRqhull_get();
  public final static int DEFsetT = qhullJNI.DEFsetT_get();
  public final static int qhDEFmerge = qhullJNI.qhDEFmerge_get();
  public final static double qh_ANGLEnone = qhullJNI.qh_ANGLEnone_get();
  public final static int qhDEFpoly = qhullJNI.qhDEFpoly_get();
  public final static int qh_ALGORITHMfault = qhullJNI.qh_ALGORITHMfault_get();
  public final static int qh_DATAfault = qhullJNI.qh_DATAfault_get();
  public final static int qhDEFrandom = qhullJNI.qhDEFrandom_get();
  public final static int qhDEFset = qhullJNI.qhDEFset_get();
  public final static int qhDEFstat = qhullJNI.qhDEFstat_get();
  public final static int DEFqhstatT = qhullJNI.DEFqhstatT_get();
}
