<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>IXDAR</groupId>
    <artifactId>IXDAR-parent</artifactId>
    <version>0.0.1</version>
  </parent>

  <artifactId>ixdar-app</artifactId>
  <version>0.0.1</version>
  <packaging>jar</packaging>

  <build>
      <sourceDirectory>src/main/java</sourceDirectory>
    <testSourceDirectory>test</testSourceDirectory>

    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <includes>
          <include>**/*.ix</include>
          <include>**/*.vs</include>
          <include>**/*.fs</include>
          <include>**/*.json</include>
          <include>**/*.png</include>
          <include>**/*.webp</include>
          <include>**/*.ico</include>
          <include>**/*.html</include>
          <include>**/*.wav</include>
          <include>**/*.dsl</include>
        </includes>
      </resource>
      <resource>
        <directory>${ixdar.asset.repo.root}/Music</directory>
        <includes>
          <include>${ixdar.audio.asset.include.pattern}</include>
        </includes>
        <targetPath>res/audio/music</targetPath>
      </resource>
      <resource>
        <directory>${ixdar.asset.repo.root}/Sfx</directory>
        <includes>
          <include>${ixdar.audio.asset.include.pattern}</include>
        </includes>
        <targetPath>res/audio/sfx</targetPath>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <release>21</release>
          <annotationProcessorPaths>
            <path>
              <groupId>IXDAR</groupId>
              <artifactId>annotations</artifactId>
              <version>0.0.1</version>
            </path>
          </annotationProcessorPaths>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <mainClass>ixdar.canvas.IxdarWindow</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>create-my-bundle</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <archive>
                <manifest>
                  <addClasspath>true</addClasspath>
                  <mainClass>ixdar.canvas.IxdarWindow</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <version>2.4</version>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
          <release>21</release>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <mainClass>ixdar.canvas.IxdarWindow</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
    </plugins>

  </build>

  <properties>
    <lwjgl.version>3.3.6</lwjgl.version>
    <native.maven.plugin.version>0.9.19</native.maven.plugin.version>
    <teavm.version>0.9.2</teavm.version>
    <ixdar.audio.asset.include.pattern>**/*.wav</ixdar.audio.asset.include.pattern>
    <ixdar.asset.repo.root>${project.basedir}/../../IxdarAssets</ixdar.asset.repo.root>
  </properties>

  <pluginRepositories>
    <pluginRepository>
      <id>graalvm-native-build-tools-snapshots</id>
      <name>GraalVM native-build-tools Snapshots</name>
      <url>https://raw.githubusercontent.com/graalvm/native-build-tools/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

  <profiles>
    <profile>
      <id>windows</id>
      <activation>
        <os>
          <family>Windows</family>
        </os>
      </activation>
      <properties>
        <lwjgl.natives>natives-windows</lwjgl.natives>
      </properties>
    </profile>
    <profile>
      <id>linux</id>
      <activation>
        <os>
          <family>Linux</family>
        </os>
      </activation>
      <properties>
        <lwjgl.natives>natives-linux</lwjgl.natives>
      </properties>
    </profile>
    <profile>
      <id>macos-aarch64</id>
      <activation>
        <os>
          <family>Mac</family>
        </os>
      </activation>
      <properties>
        <lwjgl.natives>natives-macos-arm64</lwjgl.natives>
      </properties>
    </profile>
    <profile>
      <id>asset-root-env</id>
      <activation>
        <property>
          <name>env.IXDAR_ASSET_REPO_ROOT</name>
        </property>
      </activation>
      <properties>
        <ixdar.asset.repo.root>${env.IXDAR_ASSET_REPO_ROOT}</ixdar.asset.repo.root>
      </properties>
    </profile>
    <profile>
      <id>game</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>trade-irregular-grid-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>irregular-grid-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>icosphere-save-point-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>icosphere-save-point-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>arrow-line-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>arrow-line-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>bouncing-line-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>bouncing-line-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>circle-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>circle-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>bezier-curve-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>bezier-curve-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>line-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>line-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>dashed-line-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>dashed-line-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>dashed-line-round-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>dashed-line-round-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>dashed-line-end-caps-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>dashed-line-round-end-caps-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>model-load-scene</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>model-load-canvas</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>mesh-viewer</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dsun.awt.noerasebackground=true</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.canvas.IxdarWindow</argument>
                <argument>mesh-viewer</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>export-mesh-catalog</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.geometry.mesh.documentation.ExportMeshNodeCatalog</argument>
                <argument>${project.build.directory}/mesh-node-catalog.json</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>validate-dsl</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.geometry.mesh.documentation.ValidateDsl</argument>
                <argument>${dsl.file}</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>render-dsl</id>
      <properties>
        <maven.test.skip>true</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>compile exec:exec</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.6.2</version>
            <configuration>
              <executable>java</executable>
              <workingDirectory>${project.basedir}</workingDirectory>
              <arguments>
                <argument>-enableassertions</argument>
                <argument>-XX:+IgnoreUnrecognizedVMOptions</argument>
                <argument>-XstartOnFirstThread</argument>
                <argument>-Dorg.lwjgl.util.DebugLoader=true</argument>
                <argument>-classpath</argument>
                <classpath />
                <argument>ixdar.cli.RenderDsl</argument>
                <argument>${dsl.file}</argument>
                <argument>${render.output}</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>native</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>${native.maven.plugin.version}</version>
            <extensions>true</extensions>
            <executions>
              <execution>
                <id>build-native</id>
                <goals>
                  <goal>compile-no-fork</goal>
                </goals>
                <phase>package</phase>
              </execution>
            </executions>
            <configuration>
              <imageName>gvapp</imageName>
              <mainClass>ixdar.canvas.IxdarWindow</mainClass>
              <verbose>true</verbose>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>web-teavm</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-maven-plugin</artifactId>
            <version>${teavm.version}</version>
            <executions>
              <execution>
                <id>build-teavm-js</id>
                <phase>package</phase>
                <goals>
                  <goal>compile</goal>
                </goals>
                <configuration>
                  <mainClass>ixdar.canvas.WebLauncher</mainClass>
                  <targetDirectory>${project.build.directory}/teavm/ixdar</targetDirectory>
                  <debugInformationGenerated>true</debugInformationGenerated>
                  <sourceMapsGenerated>true</sourceMapsGenerated>
                  <minifying>false</minifying>
                  <incremental>false</incremental>
                  <strict>false</strict>
                  <stopOnErrors>false</stopOnErrors>
                  <targetType>JAVASCRIPT</targetType>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.5.0</version>
            <executions>
              <execution>
                <id>patch-teavm-reflection-stubs</id>
                <phase>package</phase>
                <goals><goal>exec</goal></goals>
                <configuration>
                  <executable>python3</executable>
                  <workingDirectory>${project.basedir}</workingDirectory>
                  <arguments>
                    <argument>${project.parent.basedir}/tools/teavm-inject-reflection-stubs.py</argument>
                    <argument>${project.build.directory}/teavm/ixdar/classes.js</argument>
                  </arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <artifactId>maven-resources-plugin</artifactId>
            <version>3.3.1</version>
            <executions>
              <execution>
                <id>copy-teavm-resources</id>
                <phase>prepare-package</phase>
                <goals>
                  <goal>copy-resources</goal>
                </goals>
                <configuration>
                  <outputDirectory>${project.build.directory}/teavm/ixdar</outputDirectory>
                  <resources>
                    <resource>
                      <directory>src/main/resources</directory>
                      <filtering>false</filtering>
                      <includes>
                        <include>**/*.ix</include>
                        <include>**/*.vs</include>
                        <include>**/*.fs</include>
                        <include>**/*.json</include>
                        <include>**/*.png</include>
                        <include>**/*.webp</include>
                        <include>**/*.ico</include>
                        <include>**/*.html</include>
                        <include>**/*.wav</include>
                        <include>**/*.dsl</include>
                      </includes>
                    </resource>
                  </resources>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.0</version>
            <configuration>
              <release>21</release>
              <!-- In web build, do not exclude any sources -->
              <excludes />
            </configuration>
          </plugin>
        </plugins>
      </build>
      <dependencies>
        <dependency>
          <groupId>org.teavm</groupId>
          <artifactId>teavm-classlib</artifactId>
          <version>${teavm.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.teavm</groupId>
          <artifactId>teavm-jso</artifactId>
          <version>${teavm.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.teavm</groupId>
          <artifactId>teavm-jso-apis</artifactId>
          <version>${teavm.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.teavm</groupId>
          <artifactId>teavm-platform</artifactId>
          <version>${teavm.version}</version>
          <scope>provided</scope>
        </dependency>
        <!-- Exclude desktop-only deps from TeaVM classpath -->
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl</artifactId>
          <version>${lwjgl.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl-assimp</artifactId>
          <version>${lwjgl.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl-glfw</artifactId>
          <version>${lwjgl.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl-opengl</artifactId>
          <version>${lwjgl.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl-opengles</artifactId>
          <version>${lwjgl.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl-stb</artifactId>
          <version>${lwjgl.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl-openal</artifactId>
          <version>${lwjgl.version}</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>io.humble</groupId>
          <artifactId>humble-video-all</artifactId>
          <version>0.3.0</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>com.google.code.gson</groupId>
          <artifactId>gson</artifactId>
          <version>2.10.1</version>
          <scope>provided</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>web-gwt</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <version>3.5.0</version>
            <executions>
              <execution>
                <id>add-gwt-sources</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>add-source</goal>
                </goals>
                <configuration>
                  <sources>
                    <source>src-gwt</source>
                  </sources>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>gwt-maven-plugin</artifactId>
            <version>2.9.1</version>
            <executions>
              <execution>
                <goals>
                  <goal>compile</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <module>ixdar.web.gwt.WebApp</module>
              <logLevel>INFO</logLevel>
              <draftCompile>true</draftCompile>
              <style>OBF</style>
              <superDevMode>true</superDevMode>
              <generateJsInteropExports>true</generateJsInteropExports>
            </configuration>
          </plugin>
        </plugins>
      </build>
      <dependencies>
        <dependency>
          <groupId>com.google.gwt</groupId>
          <artifactId>gwt-user</artifactId>
          <version>2.9.0</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>com.google.gwt</groupId>
          <artifactId>gwt-dev</artifactId>
          <version>2.9.0</version>
          <scope>provided</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>test</id>
      <properties>
        <maven.test.skip>false</maven.test.skip>
      </properties>
      <build>
        <defaultGoal>test</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
              <includes>
                <include>unit/mesh/**</include>
                <include>unit/model/**</include>
                <include>unit/automation/**</include>
              </includes>
              <excludes>
                <exclude>unit/ui/**</exclude>
                <exclude>unit/visual/**</exclude>
                <exclude>unit/subgraphs/**</exclude>
              </excludes>
              <excludedGroups>heavy</excludedGroups>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>


  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.lwjgl</groupId>
        <artifactId>lwjgl-bom</artifactId>
        <version>${lwjgl.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
      <dependency>
        <groupId>IXDAR</groupId>
        <artifactId>annotations</artifactId>
        <version>0.0.1</version>
      </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.10.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
      <version>3.1</version>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-collections4</artifactId>
      <version>4.5.0-M1</version>
    </dependency>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <version>5.10.2</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>5.10.2</version>
        <scope>test</scope>
    </dependency>


    <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.14.0</version>
    </dependency>

    <dependency>
      <groupId>io.humble</groupId>
      <artifactId>humble-video-all</artifactId>
      <version>0.3.0</version>
    </dependency>
    <dependency>
      <groupId>org.joml</groupId>
      <artifactId>joml</artifactId>
      <version>1.10.8</version>
    </dependency>

    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-assimp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-glfw</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-opengl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-opengles</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-stb</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-openal</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl</artifactId>
      <classifier>${lwjgl.natives}</classifier>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-assimp</artifactId>
      <classifier>${lwjgl.natives}</classifier>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-glfw</artifactId>
      <classifier>${lwjgl.natives}</classifier>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-opengl</artifactId>
      <classifier>${lwjgl.natives}</classifier>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-opengles</artifactId>
      <classifier>${lwjgl.natives}</classifier>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-stb</artifactId>
      <classifier>${lwjgl.natives}</classifier>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-openal</artifactId>
      <classifier>${lwjgl.natives}</classifier>
    </dependency>
    <!-- Web (TeaVM) provided dependencies resolved in web-teavm profile -->
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-jso</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-jso-apis</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-platform</artifactId>
      <version>${teavm.version}</version>
    </dependency>
  </dependencies>
</project>