package ixdar.documentation;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Splices every {@code package-info.java} description into {@code ARCHITECTURE.md}
 * between the package-map markers. Bound to the Maven {@code compile} phase, so the
 * checked-in document always matches the sources; fails the build when the markers
 * are missing. Output is sorted by package name and byte-stable.
 */
public final class SpliceArchitectureDoc {

    public static final String BEGIN_MARKER = "<!-- package-map:begin (generated by SpliceArchitectureDoc; do not edit) -->";
    public static final String END_MARKER = "<!-- package-map:end -->";

    private static final Pattern PACKAGE_DECL = Pattern.compile("^package ([\\w.]+);", Pattern.MULTILINE);
    private static final Pattern JAVADOC = Pattern.compile("/\\*\\*(.*?)\\*/", Pattern.DOTALL);
    private static final Pattern CODE_TAG = Pattern.compile("\\{@(?:code|link) ([^}]*)}");

    private SpliceArchitectureDoc() {
    }

    /**
     * Rewrite the package-map section of the architecture document.
     *
     * @param args {@code args[0]} is the ARCHITECTURE.md path; the rest are source roots to scan
     * @throws IOException if a source tree cannot be walked or the document cannot be rewritten
     */
    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            System.err.println("Usage: SpliceArchitectureDoc <architecture-md> <source-root>...");
            System.exit(1);
        }
        Path doc = Path.of(args[0]);
        Map<String, String> descriptions = new TreeMap<>();
        for (int i = 1; i < args.length; i++) {
            collect(Path.of(args[i]), descriptions);
        }
        String text = Files.readString(doc);
        int begin = text.indexOf(BEGIN_MARKER);
        int end = text.indexOf(END_MARKER);
        if (begin < 0 || end < 0 || end < begin) {
            System.err.println("ARCHITECTURE.md is missing the package-map markers; refusing to continue.");
            System.exit(1);
        }
        StringBuilder section = new StringBuilder();
        section.append(BEGIN_MARKER).append('\n');
        for (Map.Entry<String, String> entry : descriptions.entrySet()) {
            section.append("- **").append(entry.getKey()).append("**: ")
                    .append(entry.getValue()).append('\n');
        }
        String updated = text.substring(0, begin) + section
                + text.substring(text.indexOf(END_MARKER));
        if (!updated.equals(text)) {
            Files.writeString(doc, updated);
        }
        System.out.println("Package map: " + descriptions.size() + " packages spliced into " + doc);
    }

    private static void collect(Path root, Map<String, String> descriptions) throws IOException {
        try (Stream<Path> files = Files.walk(root)) {
            List<Path> infos = files
                    .filter(p -> p.getFileName().toString().equals("package-info.java"))
                    .toList();
            for (Path info : infos) {
                String source = Files.readString(info);
                Matcher pkg = PACKAGE_DECL.matcher(source);
                Matcher doc = JAVADOC.matcher(source);
                if (!pkg.find() || !doc.find()) {
                    System.err.println("No package declaration or javadoc in " + info + "; refusing to continue.");
                    System.exit(1);
                }
                descriptions.put(pkg.group(1), plainText(doc.group(1)));
            }
        }
    }

    private static String plainText(String javadoc) {
        String text = javadoc.replaceAll("(?m)^\\s*\\* ?", " ");
        int firstTag = text.indexOf("\n @");
        if (firstTag >= 0) {
            text = text.substring(0, firstTag);
        }
        text = text.replace("<p>", " ");
        text = CODE_TAG.matcher(text).replaceAll("`$1`");
        return text.replaceAll("\\s+", " ").strip();
    }
}
