"""Generate agent-facing docs for the automation CLI from the single sources of truth.

Server-side commands come from the Java-built routes manifest (``automation_routes.json``, kept fresh
by the Maven build) — the Java side owns their names, flags, and descriptions. CLI-side commands come
from the decorator registry. This module rewrites a marked region of the root ``CLAUDE.md`` (one line
per command) and writes the in-depth ``ixdar_automation_cli/README.md``. It knows nothing about any
specific route or command.
"""

import inspect
from pathlib import Path

from ..cli_registry import CliCommand, CliCommandResult, cli_command, get_registry
from ..server_routes import load_manifest


BEGIN_MARKER = "<!-- BEGIN-GENERATED: automation-cli -->"
END_MARKER = "<!-- END-GENERATED: automation-cli -->"
BASE_URL = "http://127.0.0.1:47832"
CONTENTS_LINK = "[↑ Contents](#contents)"

REPO_ROOT = Path(__file__).resolve().parents[2]
CLAUDE_MD = REPO_ROOT / "CLAUDE.md"
README_MD = REPO_ROOT / "ixdar_automation_cli" / "README.md"


def _flag(param: dict) -> str:
    return "--" + param["cliName"].replace("_", "-")


def _flag_summary(route: dict) -> str:
    parts = []
    for param in route.get("params", []):
        flag = _flag(param)
        if param.get("type") == "bool" or not param.get("required"):
            parts.append(f"[{flag}]")
        else:
            parts.append(flag)
    return (" " + " ".join(parts)) if parts else ""


def _anchor(command_name: str) -> str:
    """Return the GitHub heading anchor for a command's README section.

    :param command_name: the CLI command name, e.g. ``mesh-dsl``
    :return: an in-page link target such as ``#mesh-dsl``
    """
    return f"#{command_name}"


def _table_cell(text: str) -> str:
    """Make a description safe to drop into a markdown table cell.

    :param text: a route description or command summary, possibly containing pipes or newlines
    :return: the text with pipes escaped and newlines flattened
    """
    return " ".join(text.split()).replace("|", "\\|")


def _repo_relative_link(source_path: str, line: int = 0) -> str:
    """Render a "link to code" markdown link, resolved relative to the README's directory.

    :param source_path: repo-root-relative path to the source file
    :param line: 1-based line to deep-link to, or 0 for the whole file
    :return: a markdown link labelled "link to code"
    """
    fragment = f"#L{line}" if line else ""
    return f"[link to code](../{source_path}{fragment})"


def _command_source_link(command: CliCommand) -> str:
    """Locate the Python source of a registry command and render its "link to code" link.

    :param command: the registry command whose decorated function is being documented
    :return: a markdown link to the defining module and line, or an empty string if unresolvable
    """
    source_file = inspect.getsourcefile(command.function)
    if not source_file:
        return ""
    try:
        line = inspect.getsourcelines(command.function)[1]
    except OSError:
        line = 0
    return _repo_relative_link(Path(source_file).resolve().relative_to(REPO_ROOT).as_posix(), line)


def _server_routes(manifest: dict, registry_names: set) -> list[dict]:
    routes = [r for r in manifest.get("routes", []) if r["commandName"] not in registry_names]
    return sorted(routes, key=lambda r: r["commandName"])


def _claude_block(manifest: dict) -> str:
    registry = get_registry()
    registry_names = set(registry)
    lines = [
        "_Generated by `ixdar-cli gen-docs` from Java route `describe()` and CLI command docstrings._",
        "_Do not edit by hand; see [ixdar_automation_cli/README.md](ixdar_automation_cli/README.md)._",
        "",
        "Run any command with `ixdar-cli <command> --help`. Install the global alias with "
        "`ixdar-cli install-alias` (or `bash tools/install-cli.sh`).",
        "",
        "**Server-backed commands** (generated from the automation routes manifest):",
    ]
    for route in _server_routes(manifest, registry_names):
        lines.append(f"- `ixdar-cli {route['commandName']}{_flag_summary(route)}` — {route.get('description', '')}")
    lines.append("")
    lines.append("**CLI commands** (client-side scenarios, tools, and utilities):")
    for name in sorted(registry):
        lines.append(f"- `ixdar-cli {name}` — {registry[name].summary}")
    return "\n".join(lines)


def _example_value(param: dict) -> str:
    example = param.get("example", "")
    if param.get("type") in {"int", "float"}:
        return example or "0"
    if param.get("type") == "bool":
        return example or "false"
    return f'"{example}"'


def _curl_example(route: dict) -> str:
    path = route["path"]
    if route["method"] == "GET":
        return f"curl -s {BASE_URL}{path}"
    body = ", ".join(f'"{param["name"]}": {_example_value(param)}' for param in route.get("params", []))
    return f"curl -s -XPOST {BASE_URL}{path} -d '{{{body}}}'"


def _readme(manifest: dict) -> str:
    registry = get_registry()
    registry_names = set(registry)
    out = [
        "# Ixdar Automation CLI",
        "",
        "`ixdar-cli` drives the running Ixdar app over its automation HTTP server "
        f"(`{BASE_URL}`). Server-backed subcommands are generated from the Java routes manifest "
        "(`automation_routes.json`, regenerated by every Maven build from each route's `describe()`), "
        "so the CLI and the server never drift. Client-side commands come from the `@cli_command` registry.",
        "",
        "## Install the global alias",
        "",
        "```sh",
        "bash tools/install-cli.sh      # or: uv run ixdar-cli install-alias",
        "```",
        "",
        "Creates `~/.local/bin/ixdar-cli` wrapping `uv run --project <repo> ixdar-cli`. Ensure "
        "`~/.local/bin` is on your `PATH`.",
        "",
        "## Regenerating this file",
        "",
        "```sh",
        "uv run ixdar-cli gen-docs          # rewrite the CLAUDE.md region + this README",
        "uv run ixdar-cli gen-docs --check  # CI/pre-commit drift gate",
        "```",
        "",
        "## Contents",
        "",
        "**Server-backed commands**",
        "",
    ]
    routes = _server_routes(manifest, registry_names)
    out.append("| Command | Description |")
    out.append("| --- | --- |")
    for route in routes:
        name = route["commandName"]
        out.append(f"| [`{name}`]({_anchor(name)}) | {_table_cell(route.get('description', ''))} |")
    out.append("")
    out.append("**CLI commands**")
    out.append("")
    out.append("| Command | Description |")
    out.append("| --- | --- |")
    for name in sorted(registry):
        out.append(f"| [`{name}`]({_anchor(name)}) | {_table_cell(registry[name].summary)} |")
    out.append("")
    out.append("## Server-backed commands")
    out.append("")

    for route in routes:
        out.append(f"### `{route['commandName']}`")
        out.append("")
        out.append(f"{CONTENTS_LINK} · {_repo_relative_link(route.get('sourcePath', ''))}")
        out.append("")
        out.append(route.get("description", ""))
        out.append("")
        out.append(f"- **Route:** `{route['method']} {route['path']}`")
        if route.get("params"):
            out.append("- **Flags:**")
            for param in route["params"]:
                req = "required" if param.get("required") else f"default `{param.get('default', '')}`"
                example = f", e.g. `{param['example']}`" if param.get("example") else ""
                out.append(f"  - `{_flag(param)}` ({param.get('type')}, {req}) — {param.get('help', '')}{example}")
        if route.get("responseHint"):
            out.append(f"- **Response:** `{route['responseHint']}`")
        out.append(f"- **Direct call:** `{_curl_example(route)}`")
        out.append("")

    out.append("## CLI commands")
    out.append("")
    for name in sorted(registry):
        command = registry[name]
        out.append(f"### `{name}`")
        out.append("")
        out.append(f"{CONTENTS_LINK} · {_command_source_link(command)}")
        out.append("")
        out.append(command.summary)
        out.append("")
        for param in command.params:
            out.append(f"- `{param.cli_flag}` — {param.help_text}")
        out.append("")
    return "\n".join(out)


def _splice_claude_md(text: str, block: str) -> str:
    section = f"{BEGIN_MARKER}\n{block}\n{END_MARKER}"
    if BEGIN_MARKER in text and END_MARKER in text:
        head, _, rest = text.partition(BEGIN_MARKER)
        _, _, tail = rest.partition(END_MARKER)
        return f"{head}{section}{tail}"
    separator = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return f"{text}{separator}# Automation\n\n{section}\n"


def run(check: bool = False) -> CliCommandResult:
    """Regenerate the CLAUDE.md command region and the CLI README, or check them for drift.

    :param check: when true, do not write; report whether either file is stale (non-zero exit on drift)
    :return: a result describing what was written or what drifted
    """
    manifest = load_manifest()
    if not manifest.get("routes"):
        return CliCommandResult(
            payload={"ok": False, "error": "No routes in automation_routes.json; run a Maven build first."},
            exit_code=1,
        )

    block = _claude_block(manifest)
    claude_text = CLAUDE_MD.read_text() if CLAUDE_MD.exists() else ""
    new_claude = _splice_claude_md(claude_text, block)
    readme_text = _readme(manifest) + "\n"

    claude_drifted = new_claude != claude_text
    readme_drifted = (not README_MD.exists()) or README_MD.read_text() != readme_text

    if check:
        drifted = [name for name, changed in (("CLAUDE.md", claude_drifted), ("README.md", readme_drifted)) if changed]
        return CliCommandResult(payload={"ok": not drifted, "drifted": drifted}, exit_code=1 if drifted else 0)

    if claude_drifted:
        CLAUDE_MD.write_text(new_claude)
    README_MD.write_text(readme_text)
    return CliCommandResult(
        payload={
            "ok": True,
            "claude_md_updated": claude_drifted,
            "readme_written": str(README_MD),
            "routes_documented": len(manifest["routes"]),
        }
    )


@cli_command(name="gen-docs")
def gen_docs(check: bool = False) -> CliCommandResult:
    """Regenerate the CLAUDE.md command list and the CLI README from the manifest and registry.

    :param check: Report drift without writing (CI/pre-commit gate); non-zero exit if stale.
    """
    return run(check=check)