rooms = random_rooms(seed=42, grid_w=30, grid_h=30, count=15, min_size=3, max_size=8, max_attempts=2000)
tri = delaunay_graph(geometry=rooms.geometry)
mst = minimum_spanning_tree(geometry=tri.geometry, extra_edge_prob=0.125, seed=42)
tiles = astar_corridors(geometry=tri.geometry, selection=mst.selection, grid_w=30, grid_h=30, reuse_cost=1.0, empty_cost=5.0, room_cost=50.0)
dungeon = dungeon_grid_to_mesh(geometry=tiles.geometry, cell_size=0.0667)
