rooms = random_rooms(seed=42, grid_w=30, grid_h=5, grid_d=30, count=20, min_size=3, max_size=6, max_attempts=3000)
tri = delaunay_graph(geometry=rooms.geometry)
mst = minimum_spanning_tree(geometry=tri.geometry, extra_edge_prob=0.125, seed=42)
tiles = astar_corridors_3d(geometry=tri.geometry, selection=mst.selection, grid_w=30, grid_h=5, grid_d=30, reuse_cost=1.0, empty_cost=5.0, room_cost=50.0)
dungeon = dungeon_grid_to_mesh_3d(geometry=tiles.geometry, cell_size=0.0667)
