rooms = random_rooms_3d(seed=42, grid_w=30, grid_h=5, grid_d=30, count=20, min_size=3, max_size=6, max_attempts=3000)
tri = delaunay_graph_3d(rooms=rooms.rooms)
mst = minimum_spanning_tree_3d(edges=tri.edges, rooms=rooms.rooms, extra_edge_prob=0.125, seed=42)
tiles = astar_corridors_3d(rooms=rooms.rooms, edges=mst.edges, grid_w=30, grid_h=5, grid_d=30, reuse_cost=1.0, empty_cost=5.0, room_cost=50.0)
dungeon = dungeon_grid_to_mesh_3d(tiles=tiles.tiles, cell_size=0.0667)
