# Quilting group inputs (defaults match Blender create_quilting_group in tool_quilt.py).
scale_x = float_math(operation=ADD, a=0.3, b=0.0)
scale_y = float_math(operation=ADD, a=0.3, b=0.0)
depth = float_math(operation=ADD, a=0.05, b=0.0)
rotation = float_math(operation=ADD, a=1.3089969, b=0.0)
subdivisions_f = float_math(operation=ADD, a=9.0, b=0.0)
subdivisions = float_to_int(value=subdivisions_f.result, mode=ROUND)
stitch_size = float_math(operation=ADD, a=0.003, b=0.0)
custom_depth_profile = compare(a=0.0, b=1.0, mode=EQUAL)
custom_edge_profile = compare(a=0.0, b=1.0, mode=EQUAL)
stitches = compare(a=0.0, b=1.0, mode=EQUAL)
depth_curve_default = float_curve(points="0,0,1,0.775,0.423,0.537")
edge_curve_default = float_curve(points="0.005,1,1,1,0.505,0.512")
depth_curve_custom = float_curve(points="0,0,1,1")
edge_curve_custom = float_curve(points="0,0,1,1")
base_cube = cube(size=2.0)
smooth_cube = subdivision_surface(mesh=base_cube.mesh, levels=3)
quad_sphere = spherize(mesh=smooth_cube.mesh, factor=1.0)
subdivided = subdivide_mesh(mesh=quad_sphere.mesh, levels=subdivisions.result)
pos = input_position()
norm = input_normal()
comb = combine_xyz(x=0.0, y=0.0, z=1.0)
vdot = vector_math(operation=DOT_PRODUCT, a=norm.vector, b=comb.vector)
fr = float_math(operation=FRACT, a=vdot.value, b=1.0)
sep = separate_xyz(vector=comb.vector)
cmp = compare(a=fr.result, b=0.5, mode=LESS_THAN)
sw = switch_float(switch=cmp.result, false=0.0, true=1.0)
captured = capture_attribute(geometry=subdivided.geometry, name=Distance, value=fr.result)
depth_internal = evaluate_closure(closure=depth_curve_default.closure, value=fr.result)
depth_external = evaluate_closure(closure=depth_curve_custom.closure, value=fr.result)
profile = switch_float(switch=custom_depth_profile.result, false=depth_internal.result, true=depth_external.result)
edge_internal = evaluate_closure(closure=edge_curve_default.closure, value=fr.result)
edge_external = evaluate_closure(closure=edge_curve_custom.closure, value=fr.result)
edge_factor = switch_float(switch=custom_edge_profile.result, false=edge_internal.result, true=edge_external.result)
quilted = set_position(geometry=captured.geometry, offset=comb.vector)
bbox = bound_box(geometry=quilted.geometry)
edge_verts = input_mesh_edge_vertices()
paths = input_shortest_edge_paths(end=true, edge_cost=0.1)
edge_sel = edge_paths_to_selection(start=true, next_vertex=paths.next_vertex)
deleted = delete_geometry(geometry=quilted.geometry, selection=true)
merged = merge_by_distance(geometry=deleted.geometry, distance=0.01)
curve_geo = mesh_to_curve(geometry=merged.geometry)
resampled = resample_curve(curve=curve_geo.curve, length=0.1)
bead = icosphere(radius=1.0, subdivisions=1)
tangent = input_tangent()
align_rot = align_rotation_to_vector(vector=tangent.tangent)
instanced = instance_on_points(points=resampled.curve, instance=bead.mesh, rotation=align_rot.rotation)
realized = realize_instances(geometry=instanced.geometry)
joined = join_geometry(a=realized.mesh, b=quilted.geometry)
f_idx = field_at_index(value=fr.result, index=0)
quilt_out = switch_geometry(switch=stitches.result, false=quilted.geometry, true=joined.geometry)
