# Mock graph mirroring tool_quilt.py structure (stub nodes; iterate implementations in Java).
base_cube = cube(size=2.0)
smooth_cube = subdivision_surface(mesh=base_cube.mesh, levels=3)
quad_sphere = spherize(mesh=smooth_cube.mesh, factor=1.0)
subdivided = subdivide_mesh(mesh=quad_sphere.mesh, levels=9)
pos = input_position()
norm = input_normal()
comb = combine_xyz(x=0.0, y=0.0, z=1.0)
vdot = vector_math(operation=DOT_PRODUCT, a=norm.vector, b=comb.vector)
fr = float_math(operation=FRACT, a=vdot.value, b=1.0)
sep = separate_xyz(vector=comb.vector)
cmp = compare(a=fr.result, b=0.5, mode=LESS_THAN)
sw = switch_float(switch=cmp.result, false=0.0, true=1.0)
captured = capture_attribute(geometry=subdivided.geometry, name=Distance, value=fr.result)
quilted = set_position(geometry=captured.geometry, offset=comb.vector)
bbox = bound_box(geometry=quilted.geometry)
edge_verts = input_mesh_edge_vertices()
paths = input_shortest_edge_paths(end=true, edge_cost=0.1)
edge_sel = edge_paths_to_selection(start=true, next_vertex=paths.next_vertex)
deleted = delete_geometry(geometry=quilted.geometry, selection=true)
merged = merge_by_distance(geometry=deleted.geometry, distance=0.01)
curve_geo = mesh_to_curve(geometry=merged.geometry)
resampled = resample_curve(curve=curve_geo.curve, length=0.1)
bead = icosphere(radius=1.0, subdivisions=1)
tangent = input_tangent()
align_rot = align_rotation_to_vector(vector=tangent.tangent)
instanced = instance_on_points(points=resampled.curve, instance=bead.mesh, rotation=align_rot.rotation)
realized = realize_instances(geometry=instanced.geometry)
joined = join_geometry(a=realized.mesh, b=quilted.geometry)
fc = float_curve(factor=1.0, value=0.5)
ev = evaluate_closure(value=sw.result)
f_idx = field_at_index(value=fr.result, index=0)
quilt_out = switch_geometry(switch=false, false=quilted.geometry, true=joined.geometry)
