"""Dynamic server-backed CLI commands, built at runtime from the Java routes manifest.

The manifest (``automation_routes.json``, regenerated by the Maven build) is the single source of
truth: the Java side owns every route's command name, flag names, parameter types, defaults, and
description. This module reads those verbatim and builds argparse subcommands — it contains no
knowledge of any specific route.
"""

from pathlib import Path
import json

try:
    from .cli_registry import CliCommandResult
except ImportError:
    from cli_registry import CliCommandResult


MANIFEST_PATH = Path(__file__).with_name("automation_routes.json")

_PARAM_PY_TYPE = {"int": int, "float": float, "string": str}


def load_manifest() -> dict:
    """Load the committed routes manifest, or an empty manifest if it is absent.

    The CLI still works with only its registry commands when the manifest is missing.
    """
    try:
        return json.loads(MANIFEST_PATH.read_text())
    except (OSError, ValueError):
        return {}


def server_command_map(manifest: dict, claimed_names: set) -> dict:
    """Map each server route to its Java-declared command name, skipping already-claimed names.

    :param manifest: parsed routes manifest
    :param claimed_names: command names already owned by registry commands (they win)
    :return: ordered mapping of command name to route dict
    """
    commands: dict = {}
    for route in manifest.get("routes", []):
        name = route["commandName"]
        if name in claimed_names or name in commands:
            continue
        commands[name] = route
    return dict(sorted(commands.items()))


def add_server_parsers(subparsers, command_map: dict) -> None:
    """Add one argparse subparser per dynamic server route.

    :param subparsers: the argparse subparsers action to add to
    :param command_map: name-to-route mapping from :func:`server_command_map`
    """
    for name, route in command_map.items():
        parser = subparsers.add_parser(name, help=route.get("description", ""))
        for param in route.get("params", []):
            _add_param_argument(parser, param)


def _add_param_argument(parser, param: dict) -> None:
    flag = f"--{param['cliName'].replace('_', '-')}"
    dest = param["name"]
    example = param.get("example", "")
    help_text = param.get("help", "")
    if example:
        help_text = f"{help_text} (e.g. {example})".strip()
    param_type = param.get("type", "string")

    if param_type == "bool":
        default = str(param.get("default", "")).lower() == "true"
        parser.add_argument(
            flag,
            dest=dest,
            action="store_false" if default else "store_true",
            default=default,
            help=help_text,
        )
        return

    kwargs = {"dest": dest, "type": _PARAM_PY_TYPE.get(param_type, str), "help": help_text}
    if param.get("required", False):
        kwargs["required"] = True
    else:
        kwargs["default"] = _coerce_default(param_type, param.get("default", ""))
    parser.add_argument(flag, **kwargs)


def _coerce_default(param_type: str, raw: str):
    if param_type == "int":
        return int(raw) if str(raw).strip() != "" else None
    if param_type == "float":
        return float(raw) if str(raw).strip() != "" else None
    return raw


def dispatch_server_command(route: dict, args, client) -> CliCommandResult:
    """Call the automation server for a dynamic route, returning its JSON response.

    :param route: the route dict resolved from the manifest
    :param args: parsed argparse namespace
    :param client: an ``AutomationClient``
    :return: the server response wrapped in a ``CliCommandResult``
    """
    if route["method"] == "GET":
        return CliCommandResult(payload=client.request_json(route["path"]))
    body = {param["name"]: getattr(args, param["name"]) for param in route.get("params", [])}
    return CliCommandResult(payload=client.request_json(route["path"], body))
